name: keithbelfast-training
favicon: null
layout_spectrum: 0.14392
typography_spectrum: 0.16789
title: 'Project Management tutoring | Keith Anderson'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969198'
    - '#c3bcc3'
    - '#49515e'
    - '#0b122e'
    - '#af626a'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
