name: keithbelfast-training
favicon: null
layout_spectrum: 0.49963
typography_spectrum: 0.74209
title: 'Project Management tutoring | Keith Anderson'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b180a'
    - '#8d5b20'
    - '#eaedf2'
    - '#f5af7b'
    - '#88aad0'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
