name: keithbelfast-training
favicon: null
layout_spectrum: 0.49963
typography_spectrum: 0.74209
title: 'Project Management tutoring | Keith Anderson'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#d1d1d1'
    - '#868686'
    - '#2a2a2a'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
