name: keithbelfast-training
favicon: null
layout_spectrum: 0.5353268128819764
typography_spectrum: 0.13210048829205334
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8262155302800238
  lightness: 0.46547271171584725
  saturation: 0.6398646906018257
  rhythmicContrast: 0.8410068061202765
purpose: []
